baseURL = "https://blog.personalstats.nl/"
languageCode = "en-us"
theme = "aether"
title = ""

[params]
brand = "Personalstats Blog"
description = "A blog about the development and ideas around Personalstats"